set ruler
set wildmenu
set bg=dark
set nonumber
set syntax=auto
set hlsearch
set ignorecase
set scrolloff=999
set smartcase
set incsearch
set showcmd
set laststatus=2
set ttyfast
set shortmess+=afilmnrxoOtT
set display+=lastline
