
" There options are required by vimwiki.
set nocompatible
filetype plugin on
syntax on

set encoding=utf-8

" Load only system and vimwiki's scripts.
set runtimepath=../src,$VIMRUNTIME

" Build help tags.
" helptags src/doc

" Use directories within 'test' for storing wiki and html.
let wiki = {}
let wiki.path = getcwd().'/wiki'
let wiki.path_html = getcwd().'/html'
let wiki.template_path = getcwd().'/'
let wiki.template_default = 'empty'
let wiki.template_ext = '.tpl'
"let wiki.maxhi = 1
let g:vimwiki_list = [wiki]

let g:vimwiki_camel_case = 0
"let g:vimwiki_debug = 2
